from selenium.webdriver.common.by import By

class OrderPartLocators:
    upper_button_order = [By.XPATH, '//button[text()="Заказать"]']
    lower_button_order = [By.XPATH, '(//button[text()="Заказать"])[2]']
    field_name = [By.XPATH, '//input[@placeholder="* Имя"]']
    field_surname = [By.XPATH, '//input[@placeholder="* Фамилия"]']
    field_address = [By.XPATH, '//input[@placeholder="* Адрес: куда привезти заказ"]']
    field_metro_station = [By.XPATH, '//input[@placeholder="* Станция метро"]']
    exact_metro_station_1 = [By.XPATH, '//button[@value ="1"]']
    exact_metro_station_2 = [By.XPATH, '//button[@value ="2"]']
    field_phone = [By.XPATH, '//input[@placeholder="* Телефон: на него позвонит курьер"]']
    field_date_of_start_using = [By.XPATH, '//input[@placeholder="* Когда привезти самокат"]']
    exact_date_of_using = [By.XPATH, '//div[@label="Choose понедельник, 16-е января 2023 г."]']
    field_period_of_using = [By.CLASS_NAME, "Dropdown-placeholder"]
    exact_period_of_using = [By.XPATH, '//div[text()="сутки"]']
    field_black_color_of_scooter = [By.ID, "black"]
    field_grey_color_of_scooter = [By.ID, "grey"]
    window_make_order = [By.LINK_TEXT, "Хотите оформить заказ?"]
    window_order_is_successful = [By.XPATH, '//button[text()="Посмотреть статус"]']
    yes_button = [By.XPATH, '//button[text()="Да"]']
    button_continue = [By.XPATH, '//button[text()="Далее"]']
    close_calendar = [By.XPATH, '//div[text()="Про аренду"]']